### ISSUE TITLE
Generate md/swagger.yaml from comments?

### ISSUE THREAD

**Issue by Pritoj** [bee-travels/openapi-comment-parser#19]
## What am I trying to accomplish
We have various github repos and I would like to generate the docs in an md file that can then be used to refer to the API. Currently I have these comments and from them I can generate the swagger.yml file. Is it possible to do something similar with this package?

Would it be possible to generate a swagger file from the spec instead of exposing the endpoint.

**Comment by bourdakos1** [comment]
Hi there,

Are you asking if it’s possible to export a swagger yaml instead of serving swagger ui?

If so yes, you can use the CLI to export a swagger json file (we can add support for yaml too if you want). Or you can use it inline in your code and write the swagger object to a yaml file instead of passing it to swagger ui

Hope this helps :)

**Comment by bourdakos1** [comment]
@Pritoj here is an example how to do it in code:
```js
const fs = require('fs');
const yaml = require('js-yaml');
const openapi = require('openapi-comment-parser');

const spec = openapi();

fs.writeFileSync('swagger.yml', yaml.dump(spec));
```

**Comment by Pritoj** [comment]
I think this is exactly what I was looking for. Thanks so much for this and being so quick. I can close this now ✅
